/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Sphere004: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Sphere010: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Sphere011: THREE.Mesh;
    Cylinder013: THREE.Mesh;
    Sphere012: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Sphere013: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Sphere016: THREE.Mesh;
    Cylinder016: THREE.Mesh;
  };
  materials: {
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "Sphere.004Action"
  | "Cylinder.006Action"
  | "Sphere.006Action"
  | "Cylinder.007Action"
  | "Sphere.007Action"
  | "Cylinder.008Action"
  | "Sphere.008Action"
  | "Sphere.002Action"
  | "Cylinder.005Action"
  | "Sphere.005Action"
  | "Cylinder.009Action"
  | "Sphere.009Action"
  | "Cylinder.010Action"
  | "Sphere.010Action"
  | "Sphere.001Action"
  | "Cylinder.011Action"
  | "Sphere.003Action"
  | "Cylinder.012Action"
  | "Sphere.011Action"
  | "Cylinder.013Action"
  | "Sphere.012Action"
  | "SphereAction"
  | "Cylinder.002Action"
  | "Cylinder.003Action"
  | "Cylinder.004Action"
  | "Sphere.013Action"
  | "Cylinder.001Action.001"
  | "Sphere.013Action.004"
  | "Cylinder.001Action.005"
  | "AreaAction"
  | "Area.001Action";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF("/SN1.gltf") as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Sphere004"
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-1.96, -1.64, -1.02]}
        rotation={[1.75, 0, -0.81]}
        scale={0.64}
      />
      <mesh
        name="Cylinder006"
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[-1.49, -1.68, -2.05]}
        rotation={[1.6, -0.14, -2.74]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere006"
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[-1.07, -1.73, -2.97]}
        rotation={[1.75, 0, -0.81]}
        scale={0.51}
      />
      <mesh
        name="Cylinder007"
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[-2.4, -0.69, -0.93]}
        rotation={[0.49, -0.7, 0.54]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere007"
        geometry={nodes.Sphere007.geometry}
        material={nodes.Sphere007.material}
        position={[-2.83, 0.19, -0.8]}
        rotation={[1.72, 0.01, -0.8]}
        scale={0.51}
      />
      <mesh
        name="Cylinder008"
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[-2.66, -2.51, -0.96]}
        rotation={[-2.86, -0.51, 0.78]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere008"
        geometry={nodes.Sphere008.geometry}
        material={nodes.Sphere008.material}
        position={[-3.33, -3.27, -0.87]}
        rotation={[1.78, -0.02, -0.8]}
        scale={0.51}
      />
      <mesh
        name="Sphere002"
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[1.84, -1.57, -1.02]}
        rotation={[-1.76, -0.36, 2.27]}
        scale={0.64}
      />
      <mesh
        name="Cylinder005"
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[1.39, -1.7, -2.05]}
        rotation={[-1.6, -0.22, 0.39]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere005"
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[0.99, -1.81, -2.97]}
        rotation={[-1.76, -0.36, 2.27]}
        scale={0.51}
      />
      <mesh
        name="Cylinder009"
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[2.59, -2.31, -0.93]}
        rotation={[-0.7, 0.49, -2.23]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere009"
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[3.3, -2.97, -0.8]}
        rotation={[-1.73, -0.37, 2.29]}
        scale={0.51}
      />
      <mesh
        name="Cylinder010"
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[2.19, -0.51, -0.96]}
        rotation={[3.07, 0.57, -2.77]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere010"
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[2.55, 0.44, -0.87]}
        rotation={[-1.79, -0.33, 2.27]}
        scale={0.51}
      />
      <mesh
        name="Sphere001"
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.03, 2.27, -1.31]}
        rotation={[3.06, -1.39, 0.65]}
        scale={0.64}
      />
      <mesh
        name="Cylinder011"
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[0.01, 1.84, -2.36]}
        rotation={[-1.78, -1.44, 0.16]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere003"
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[-0.03, 1.45, -3.29]}
        rotation={[3.06, -1.39, 0.65]}
        scale={0.51}
      />
      <mesh
        name="Cylinder012"
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[0.97, 2.73, -1.22]}
        rotation={[-0.72, -0.38, -1.34]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere011"
        geometry={nodes.Sphere011.geometry}
        material={nodes.Sphere011.material}
        position={[1.84, 3.17, -1.07]}
        rotation={[2.97, -1.42, 0.56]}
        scale={0.51}
      />
      <mesh
        name="Cylinder013"
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[-0.85, 2.95, -1.23]}
        rotation={[-2.58, 0.24, 2.2]}
        scale={[0.15, 0.61, 0.15]}
      />
      <mesh
        name="Sphere012"
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[-1.63, 3.6, -1.12]}
        rotation={[-3.1, -1.37, 0.77]}
        scale={0.51}
      />
      <mesh
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        material={materials["Material.002"]}
        scale={0.64}
      />
      <mesh
        name="Cylinder002"
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0, 1.14, -0.64]}
        rotation={[2.61, 0, 0]}
        scale={[0.13, 0.78, 0.13]}
      />
      <mesh
        name="Cylinder003"
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-0.95, -0.85, -0.49]}
        rotation={[-2.65, 0.01, -2.33]}
        scale={[0.13, 0.78, 0.13]}
      />
      <mesh
        name="Cylinder004"
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.89, -0.78, -0.53]}
        rotation={[-2.66, 0.04, 2.34]}
        scale={[0.13, 0.78, 0.13]}
      />
      <mesh
        name="Sphere013"
        geometry={nodes.Sphere013.geometry}
        material={materials["Material.007"]}
        position={[0, 0, 3.19]}
        scale={0.6}
      />
      <mesh
        name="Cylinder014"
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[0, 0, 1.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.13, 0.52, 0.13]}
      />
      <mesh
        name="Sphere016"
        geometry={nodes.Sphere016.geometry}
        material={materials["Material.008"]}
        position={[0, 0, -7.25]}
        scale={0.6}
      />
      <mesh
        name="Cylinder016"
        geometry={nodes.Cylinder016.geometry}
        material={materials.Material}
        position={[0, 0, 2.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.13, 0.52, 0.13]}
      />
    </group>
  );
}

useGLTF.preload("/SN1.gltf");
