/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Sphere004: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere: THREE.Mesh;
    Sphere013: THREE.Mesh;
    Sphere004_1: THREE.Mesh;
    Sphere004_2: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder002: THREE.Mesh;
  };
  materials: {
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "Sphere.004Action"
  | "Sphere.002Action"
  | "Sphere.001Action"
  | "SphereAction"
  | "Sphere.013Action"
  | "Sphere.013Action.004"
  | "AreaAction"
  | "Area.001Action"
  | "CylinderAction"
  | "Cylinder.001Action"
  | "Cylinder.005Action"
  | "Cylinder.006Action"
  | "Cylinder.003Action.001"
  | "Cylinder.004Action.001"
  | "Cylinder.002Action.001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF("/SN2.gltf") as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Sphere004"
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-1.96, -1.64, -1.02]}
        rotation={[1.75, 0, -0.81]}
        scale={0.64}
      />
      <mesh
        name="Sphere002"
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[1.84, -1.57, -1.02]}
        rotation={[-1.76, -0.36, 2.27]}
        scale={0.64}
      />
      <mesh
        name="Sphere001"
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.03, 2.27, -1.31]}
        rotation={[3.06, -1.39, 0.65]}
        scale={0.64}
      />
      <mesh
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        material={materials["Material.002"]}
        scale={0.64}
      />
      <mesh
        name="Sphere013"
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[0, 0, 3.19]}
        scale={0.6}
      />
      <group name="Sphere016" position={[0, 0, -5.51]} scale={0.6}>
        <mesh
          geometry={nodes.Sphere004_1.geometry}
          material={nodes.Sphere004_1.material}
        />
        <mesh
          geometry={nodes.Sphere004_2.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <mesh
        name="Cylinder"
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, 0, -0.04]}
        rotation={[-1.57, 0, 0]}
        scale={[0.13, 0.51, 0.13]}
      />
      <mesh
        name="Cylinder001"
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0, 0, -5.49]}
        rotation={[-1.57, 0, 0]}
        scale={[0.13, 0.53, 0.13]}
      />
      <mesh
        name="Cylinder005"
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[0, 0, 2.16]}
        rotation={[-1.57, 0, 0]}
        scale={[0.13, 0.56, 0.13]}
      />
      <mesh
        name="Cylinder006"
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[0, 0, 1.04]}
        rotation={[-1.57, 0, 0]}
        scale={[0.13, 0.56, 0.13]}
      />
      <mesh
        name="Cylinder003"
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-0.97, -0.85, -0.53]}
        rotation={[0.59, 0, -0.81]}
        scale={[0.13, 0.88, 0.13]}
      />
      <mesh
        name="Cylinder004"
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.86, -0.73, -0.49]}
        rotation={[0.55, 0.06, 0.73]}
        scale={[0.13, 0.86, 0.13]}
      />
      <mesh
        name="Cylinder002"
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.04, 1.16, -0.69]}
        rotation={[-0.56, 0, 0]}
        scale={[0.13, 0.86, 0.13]}
      />
    </group>
  );
}

useGLTF.preload("/SN2.gltf");
