/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Sphere003: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere005: THREE.Mesh
    Sphere006: THREE.Mesh
    Sphere007: THREE.Mesh
    Sphere008: THREE.Mesh
    Sphere009: THREE.Mesh
    Sphere010: THREE.Mesh
    Sphere011: THREE.Mesh
    Sphere012: THREE.Mesh
    Sphere013: THREE.Mesh
    Sphere014: THREE.Mesh
    Sphere015: THREE.Mesh
    Sphere016: THREE.Mesh
    Sphere017: THREE.Mesh
    Sphere018: THREE.Mesh
    Sphere019: THREE.Mesh
    Sphere020: THREE.Mesh
    Sphere021: THREE.Mesh
    Sphere022: THREE.Mesh
    Sphere023: THREE.Mesh
    Sphere024: THREE.Mesh
    Sphere025: THREE.Mesh
    Sphere026: THREE.Mesh
    Sphere027: THREE.Mesh
    Sphere028: THREE.Mesh
    Sphere029: THREE.Mesh
    Sphere030: THREE.Mesh
    Sphere031: THREE.Mesh
    Sphere032: THREE.Mesh
    Sphere033: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/3-D-hexagonal-ABA.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-0.61, 0, -0.99]}
        rotation={[0, 0.55, 0]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[1.14, 0, -0.03]}
        rotation={[0, 0.55, 0]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[-0.56, 0, 1.03]}
        rotation={[0, 0.55, 0]}
      />
      <mesh geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[1.72, 3.2, 1]} />
      <mesh geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[1.71, 3.2, -0.98]} />
      <mesh geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[0, 3.2, 1.97]} />
      <mesh geometry={nodes.Sphere006.geometry} material={nodes.Sphere006.material} position={[-1.71, 3.2, 1]} />
      <mesh geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[-1.72, 3.2, -0.98]} />
      <mesh geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[0, 3.2, -1.97]} />
      <mesh geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[0, 3.2, 0]} />
      <mesh geometry={nodes.Sphere010.geometry} material={nodes.Sphere010.material} position={[1.72, -3.15, 1]} />
      <mesh geometry={nodes.Sphere011.geometry} material={nodes.Sphere011.material} position={[1.71, -3.15, -0.98]} />
      <mesh geometry={nodes.Sphere012.geometry} material={nodes.Sphere012.material} position={[0, -3.15, 1.97]} />
      <mesh geometry={nodes.Sphere013.geometry} material={nodes.Sphere013.material} position={[-1.71, -3.15, 1]} />
      <mesh geometry={nodes.Sphere014.geometry} material={nodes.Sphere014.material} position={[-1.72, -3.15, -0.98]} />
      <mesh geometry={nodes.Sphere015.geometry} material={nodes.Sphere015.material} position={[0, -3.15, -1.97]} />
      <mesh geometry={nodes.Sphere016.geometry} material={nodes.Sphere016.material} position={[0, -3.15, 0]} />
      <mesh
        geometry={nodes.Sphere017.geometry}
        material={nodes.Sphere017.material}
        position={[-0.61, 0, 21.63]}
        rotation={[0, 0.55, 0]}
      />
      <mesh
        geometry={nodes.Sphere018.geometry}
        material={nodes.Sphere018.material}
        position={[1.14, 0, 22.59]}
        rotation={[0, 0.55, 0]}
      />
      <mesh
        geometry={nodes.Sphere019.geometry}
        material={nodes.Sphere019.material}
        position={[-0.56, 0, 23.65]}
        rotation={[0, 0.55, 0]}
      />
      <mesh
        geometry={nodes.Sphere020.geometry}
        material={nodes.Sphere020.material}
        position={[1.05, 1.81, 24.3]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere021.geometry}
        material={nodes.Sphere021.material}
        position={[1.97, 1.81, 22.56]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere022.geometry}
        material={nodes.Sphere022.material}
        position={[-0.92, 1.81, 24.36]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere023.geometry}
        material={nodes.Sphere023.material}
        position={[-1.98, 1.81, 22.7]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere024.geometry}
        material={nodes.Sphere024.material}
        position={[-1.05, 1.81, 20.94]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere025.geometry}
        material={nodes.Sphere025.material}
        position={[0.93, 1.81, 20.88]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere026.geometry}
        material={nodes.Sphere026.material}
        position={[0, 1.81, 22.61]}
        rotation={[0, -0.49, 0]}
      />
      <mesh
        geometry={nodes.Sphere027.geometry}
        material={nodes.Sphere027.material}
        position={[1.09, -1.72, 24.27]}
        rotation={[0, -0.46, 0]}
      />
      <mesh
        geometry={nodes.Sphere028.geometry}
        material={nodes.Sphere028.material}
        position={[1.97, -1.72, 22.51]}
        rotation={[0, -0.46, 0]}
      />
      <mesh
        geometry={nodes.Sphere029.geometry}
        material={nodes.Sphere029.material}
        position={[-0.88, -1.72, 24.38]}
        rotation={[0, -0.46, 0]}
      />
      <mesh
        geometry={nodes.Sphere030.geometry}
        material={nodes.Sphere030.material}
        position={[-1.98, -1.72, 22.74]}
        rotation={[0, -0.46, 0]}
      />
      <mesh
        geometry={nodes.Sphere031.geometry}
        material={nodes.Sphere031.material}
        position={[-1.09, -1.72, 20.96]}
        rotation={[0, -0.46, 0]}
      />
      <mesh
        geometry={nodes.Sphere032.geometry}
        material={nodes.Sphere032.material}
        position={[0.89, -1.72, 20.85]}
        rotation={[0, -0.46, 0]}
      />
      <mesh geometry={nodes.Sphere033.geometry} material={nodes.Sphere033.material} position={[0, -1.72, 22.61]} />
    </group>
  )
}

useGLTF.preload('/3-D-hexagonal-ABA.gltf')
