/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Sphere003: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere005: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere001: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/tbp_t shape_2lp.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.003']} />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[3.1, 0, 1.74]}
        scale={0.88}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[1.58, 0, 0.98]}
        rotation={[Math.PI / 2, 0, -Math.PI / 3]}
        scale={[0.26, 1, 0.26]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[0.13, 1.83, 0]}
        rotation={[-0.03, -0.84, -0.05]}
        scale={[0.26, 1, 0.26]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.11, -1.74, 0.05]}
        rotation={[0.05, -0.84, 0.05]}
        scale={[0.26, 1, 0.26]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.21, 3.54, 0.01]}
        rotation={[0, 0, -0.03]}
        scale={0.88}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[0.2, -3.34, 0.06]}
        rotation={[0, 0, 0.04]}
        scale={0.88}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[0, 0, -2.48]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        position={[-2.27, -0.05, 1.35]}
        rotation={[Math.PI / 2, 0, -2.06]}
      />
    </group>
  )
}

useGLTF.preload('/tbp_t shape_2lp.gltf')
