/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Cylinder: THREE.Mesh
    Sphere001: THREE.Mesh
    Cylinder001: THREE.Mesh
    Sphere002: THREE.Mesh
    Cylinder002: THREE.Mesh
    Sphere003: THREE.Mesh
    Cylinder003: THREE.Mesh
    Sphere004: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/tetrahedral.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, 1.81, 0]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0, 3.45, 0]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[1.73, -0.6, 0.36]}
        rotation={[0, -0.21, -1.92]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[3.28, -1.12, 0.71]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-0.38, -0.65, -1.56]}
        rotation={[-0.15, -1.31, 1.73]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[-0.87, -1.15, -3.04]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-1.06, -0.62, 1.39]}
        rotation={[1.63, 0.29, 0.71]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-2.1, -1.11, 2.61]}
        scale={0.85}
      />
    </group>
  )
}

useGLTF.preload('/tetrahedral.gltf')
