/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Sphere003: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere005: THREE.Mesh
    Sphere006: THREE.Mesh
    Sphere007: THREE.Mesh
    Sphere008: THREE.Mesh
    Sphere009: THREE.Mesh
    Sphere010: THREE.Mesh
    Sphere011: THREE.Mesh
    Sphere012: THREE.Mesh
    Sphere013: THREE.Mesh
    Sphere014: THREE.Mesh
    Sphere015: THREE.Mesh
    Sphere016: THREE.Mesh
    Sphere017: THREE.Mesh
    Sphere018: THREE.Mesh
    Sphere019: THREE.Mesh
    Sphere020: THREE.Mesh
    Sphere021: THREE.Mesh
    Sphere022: THREE.Mesh
    Sphere023: THREE.Mesh
    Sphere024: THREE.Mesh
    Sphere025: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/3-D-hexagonal-ABCABC.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-0.64, -1.59, 6.7]}
        rotation={[0, 0.53, 0]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[1.11, -1.59, 7.66]}
        rotation={[0, 0.53, 0]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[-0.63, -1.59, 8.7]}
        rotation={[0, 0.53, 0]}
      />
      <mesh geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[-0.01, 1.63, 7.67]} />
      <mesh geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[0, 1.63, 5.66]} />
      <mesh geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[1.77, 1.63, 6.66]} />
      <mesh geometry={nodes.Sphere006.geometry} material={nodes.Sphere006.material} position={[1.77, 1.63, 8.71]} />
      <mesh geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[0, 1.63, 9.73]} />
      <mesh geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[-1.76, 1.63, 8.7]} />
      <mesh geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[-1.76, 1.63, 6.68]} />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[-1.17, 4.93, 7.61]}
        rotation={[0, 1.5, 0]}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={nodes.Sphere011.material}
        position={[0.62, 4.93, 6.71]}
        rotation={[0, 1.5, 0]}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[0.5, 4.93, 8.73]}
        rotation={[0, 1.5, 0]}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[-0.64, -0.02, -10]}
        rotation={[0, 0.53, 0]}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={nodes.Sphere014.material}
        position={[1.11, -0.02, -9.04]}
        rotation={[0, 0.53, 0]}
      />
      <mesh
        geometry={nodes.Sphere015.geometry}
        material={nodes.Sphere015.material}
        position={[-0.63, -0.02, -8]}
        rotation={[0, 0.53, 0]}
      />
      <mesh geometry={nodes.Sphere016.geometry} material={nodes.Sphere016.material} position={[-0.01, 1.63, -9.04]} />
      <mesh geometry={nodes.Sphere017.geometry} material={nodes.Sphere017.material} position={[0, 1.63, -11.04]} />
      <mesh geometry={nodes.Sphere018.geometry} material={nodes.Sphere018.material} position={[1.77, 1.63, -10.04]} />
      <mesh geometry={nodes.Sphere019.geometry} material={nodes.Sphere019.material} position={[1.77, 1.63, -7.99]} />
      <mesh geometry={nodes.Sphere020.geometry} material={nodes.Sphere020.material} position={[0, 1.63, -6.97]} />
      <mesh geometry={nodes.Sphere021.geometry} material={nodes.Sphere021.material} position={[-1.76, 1.63, -8]} />
      <mesh geometry={nodes.Sphere022.geometry} material={nodes.Sphere022.material} position={[-1.76, 1.63, -10.03]} />
      <mesh
        geometry={nodes.Sphere023.geometry}
        material={nodes.Sphere023.material}
        position={[-1.17, 3.33, -9.09]}
        rotation={[0, 1.5, 0]}
      />
      <mesh
        geometry={nodes.Sphere024.geometry}
        material={nodes.Sphere024.material}
        position={[0.62, 3.33, -9.99]}
        rotation={[0, 1.5, 0]}
      />
      <mesh
        geometry={nodes.Sphere025.geometry}
        material={nodes.Sphere025.material}
        position={[0.5, 3.33, -7.97]}
        rotation={[0, 1.5, 0]}
      />
    </group>
  )
}

useGLTF.preload('/3-D-hexagonal-ABCABC.gltf')
