/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Cylinder001: THREE.Mesh
    Sphere002: THREE.Mesh
    Cylinder002: THREE.Mesh
    Sphere003: THREE.Mesh
    Cylinder003: THREE.Mesh
    Sphere004: THREE.Mesh
    Icosphere: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/tetrahedral_trigonal pyramidal_one lp.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[1.48, -0.72, 0.36]}
        rotation={[-0.02, -0.21, -2.01]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[2.98, -1.38, 0.71]}
        rotation={[0, 0, -0.09]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-0.38, -0.75, -1.46]}
        rotation={[-0.23, -1.31, 1.73]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[-0.87, -1.36, -2.9]}
        rotation={[-0.08, 0, 0]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-1.06, -0.75, 1.34]}
        rotation={[1.76, 0.29, 0.71]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-2.1, -1.39, 2.49]}
        rotation={[0.13, 0, 0]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials['Material.004']}
        position={[0, 2.27, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.88}
      />
    </group>
  )
}

useGLTF.preload('/tetrahedral_trigonal pyramidal_one lp.gltf')
