/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Cylinder: THREE.Mesh
    Sphere001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Sphere003: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere001: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/tetrahedral_bent_2 lp.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, 1.6, -0.71]}
        rotation={[-0.39, 0, 0]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0, 3.11, -1.34]}
        rotation={[-0.39, 0, 0]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-0.38, -0.65, -1.56]}
        rotation={[-0.15, -1.31, 1.73]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[-0.87, -1.15, -3.04]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[-1.33, -0.6, 1.71]}
        rotation={[-1.23, 0.09, -0.6]}
        scale={0.87}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        position={[2.29, -0.55, 0.31]}
        rotation={[-1.62, 0.21, 1.42]}
        scale={0.87}
      />
    </group>
  )
}

useGLTF.preload('/tetrahedral_bent_2 lp.gltf')
