/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Sphere002: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Sphere004: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Sphere010: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/staggered.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[0.12, 0.13, 0.05]}
        rotation={[1.61, -1.39, 0.04]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0.14, 0.1, 3.06]}
        rotation={[-1.58, -0.71, 3.14]}
        scale={[0.24, 2.32, 0.24]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.01, -1.63, -0.55]}
        rotation={[-1.8, -1.54, 0.99]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.01, -3.21, -1.08]}
        rotation={[1.61, -1.39, 0.04]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[1.53, 0.79, -0.59]}
        rotation={[-1.53, -0.43, -1.26]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[3.07, 1.59, -1.07]}
        rotation={[1.61, -1.39, 0.04]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[-1.5, 0.93, -0.57]}
        rotation={[2.87, 0.12, 2.13]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[-2.83, 1.69, -1.07]}
        rotation={[1.61, -1.39, 0.04]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={nodes.Sphere007.material}
        position={[0.15, 0.09, 6.15]}
        rotation={[1.58, 0.28, 3.14]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-1.38, -0.76, 6.74]}
        rotation={[1.58, 0.49, 1.22]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={nodes.Sphere008.material}
        position={[-2.86, -1.48, 7.27]}
        rotation={[1.58, 0.28, 3.14]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[0.11, 1.69, 6.81]}
        rotation={[-2.48, 1.52, 2.79]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[0.1, 3.23, 7.32]}
        rotation={[1.58, 0.28, 3.14]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[1.59, -0.96, 6.75]}
        rotation={[0.03, -0.3, -2.14]}
        scale={[0.24, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[2.93, -1.84, 7.24]}
        rotation={[1.58, 0.28, 3.14]}
        scale={0.85}
      />
    </group>
  );
}

useGLTF.preload("/staggered.gltf");
